# conf-file /usr/local/etc/smartdns.conf

bind 0.0.0.0:53
force-qtype-SOA 65
log-level info

address /*.internal/127.0.0.1
hosts-file /etc/hosts

server-tls 8.8.8.8
server-tls 1.1.1.1
server-tls 223.5.5.5 -group servers-inwall -exclude-default-group
server-tls 223.6.6.6 -group servers-inwall -exclude-default-group

domain-set -name domains-uncensored -file /usr/local/etc/domains-uncensored.txt
nameserver /domain-set:domains-uncensored/servers-inwall
