timeout 0.25
quiet: yes

/Boot A
   protocol: linux
   kernel_path: boot():/a/vmlinuz
   module_path: boot():/a/initrd
   cmdline: rootflags=subvol=@a/@ quiet splash plymouth.use-simpledrm=0

/Boot B
   protocol: linux
   kernel_path: boot():/b/vmlinuz
   module_path: boot():/b/initrd
   cmdline: rootflags=subvol=@b/@ quiet splash plymouth.use-simpledrm=0

